# 默认使用配置
spring:
  profiles:
#    active: ${spring.profiles.active}
    active: dev

  #  数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.79.94.90:3306/central_certification?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

  # redis 配置
  redis:
    database: 0
    host: 120.79.94.90
    port: 6379
    password: redis123
    jedis:
      pool:
#        max-active: 100
#        max-idle: 10
        max-wait: 100000
    timeout: 5000
  # 邮件配置
  mail:
    host: smtp.qq.com
    username: 799957684@qq.com
    # 设置密码，该处的密码是QQ邮箱开启SMTP的授权码而非QQ密码
    password: fedpazqryszubeij
    properties:
      mail:
        smtp:
          # 设置是否需要认证，如果为true,那么用户名和密码就必须的，
          # 如果设置false，可以不设置用户名和密码，当然也得看你的对接的平台是否支持无密码进行访问的。
          auth: true
          ## STARTTLS[1]  是对纯文本通信协议的扩展。它提供一种方式将纯文本连接升级为加密连接（TLS或SSL），而不是另外使用一个端口作加密通信。
          starttls:
            enable: true
            required: true
          # 阿里云禁用25 端口，这里用465，465 是ssl 端口，所以用ssl 连接
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
    port: 465

mybatis:
  mapper-locations: 'classpath:mapper/**/*.xml'
  mapper-scan: 'com.jike'
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: false
    auto-mapping-behavior: partial
    safe-row-bounds-enabled: false
    local-cache-scope: session
    jdbc-type-for-null: other
    lazy-load-trigger-methods: equals,clone,hashCode,toString
    vfs-impl: org.mybatis.spring.boot.autoconfigure.SpringBootVFS
  plugins:
    pagehelper:
      dialect: mysql
      offsetAsPageNum: true
      rowBoundsWithCount: true
      pageSizeZero: true
      reasonable: false
      parabs: 'pageNum=pageHelperStart;pageSize=pageHelperRows;'
      supportMethodsArguments: false
      returnPageInfo: none

# swagger 打开配置
swagger:
  enable: true