spring:
  #  数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.79.94.90:3306/central_certification?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

  # redis 配置
  redis:
    database: 0
    host: 120.79.94.90
    port: 6379
    password: redis123